#!/usr/bin/env bash
# manages 'manage_my_process'

if [ $# -gt 0 ]
then
	if [ "$1" == "start" ]
	then
		./manage_my_process & touch /var/run/my_process.pid
#		echo $(pgrep -f manage_my_process) > /var/run/my.process.pid
		echo "$!" > /var/run/my_process.pid
		echo "manage_my_process started"
	elif [ "$1" == "stop" ]
	then
#		kill $(pgrep -f manage_my_process)
		echo ",amanage_my_process stopped"
		kill "$(cat /var/run/my_process.pid)"
		rm -f /var/run/my_process.pid
	elif [ "$1" == "restart" ]
	then
#		kill $(pgrep -f manage_,y_process)
		kill "$(cat /var/run/my_process.pi)"
		rm -f /var/run/my_process.pid
		./manage_my_process &
#		echo $(pgrep -f manage_my_process) > /var/run/my_process.pid
		touch /var/run/my_process.pid
		echo "$!" > /var/run/my_process.pid
		echo "manage_my_process restarted"
	else
		eco "Usage: manage_my_process {start|stop|reatsrt}"
	fi
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
