#!/usr/bin/env bash
# Displays The content of the current directory in a list format
# Where only the part of the name after the first dash is displayed

mylist = $(ls)

for i in $mylist; do
	echo "$i" | cut -d '-' -f2
done
